Repository Sifon98/GruppUppgift, pull requests merged in 2020-09, with the labels that each got.

#1 First commit
  README.md
Labels: ready for merge

#2 Initcontact
  Joels-kontakt.pdf
  contact.css
  contact.html
Labels: documentation, pending review, ready for merge

#10 About alex
  CSS/Normalize.css
  CSS/about.css
  HTML/about.html
  img/Logo.png
  img/bg-blue.jpg
  img/bg-blue1.jpg
  js/parallax.js
Labels: ready for merge

#11 Initcontact
  contact.css
  contact.html
  imgJoel/avatar.jpg
  imgJoel/f logo1.png
  imgJoel/logga.png
  imgJoel/m logo1.png
  imgJoel/p logo.png
Labels: good first issue

#18 About
  CSS/about.css
  HTML/about.html
  img/alex.jpg
Labels: pending review, ready for merge

#16 Contact
  CSS/contact.css
  HTML/contact.html
Labels: ready for merge

#19 footer added
  CSS/contact.css
  HTML/contact.html
Labels: ready for merge
